#!/usr/bin/env python3
"""Record VT fixture cases from a real PTY.

A recorded fixture with no recording tool is unreproducible, so the recorder
lives in the repo next to the fixtures it writes. Re-recording a case is::

    scripts/capture-vt.py claude-code-startup

and re-recording everything is::

    scripts/capture-vt.py --all

The point of recording rather than hand-writing escape sequences is fidelity:
hand-written sequences only test what the author already knew about. Claude Code
emits synchronized-output brackets, kitty keyboard flags, and OSC title updates
that nobody writes into a test by hand.

Each case becomes `fixtures/vt/<name>/` holding `input.bin` (the raw PTY output)
and `meta.json` (initial size, any resize applied partway, and provenance).
`expected.json` is authored by hand — it is an independent reading of the bytes,
not a dump of what an emulator produced, for the same reason the protocol
fixtures were not generated by the crate under test.
"""

from __future__ import annotations

import argparse
import errno
import fcntl
import json
import os
import platform
import pty
import select
import shutil
import struct
import sys
import termios
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VT_DIR = os.path.join(ROOT, "fixtures", "vt")

DEFAULT_COLS = 100
DEFAULT_ROWS = 30


def set_size(fd: int, cols: int, rows: int) -> None:
    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))


def record(
    argv,
    *,
    cwd=None,
    seconds=8.0,
    cols=DEFAULT_COLS,
    rows=DEFAULT_ROWS,
    keys=(),
    resize=None,
    env=None,
):
    """Run `argv` on a PTY and return (output_bytes, resizes).

    `keys` is a sequence of (delay_seconds, bytes) written to the PTY. `resize`
    is an optional (delay_seconds, cols, rows); the byte offset at which it
    landed is recorded so replay can apply it at the same point in the stream.
    """
    pid, fd = pty.fork()
    if pid == 0:
        child_env = {
            "TERM": "xterm-256color",
            "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
            "HOME": os.environ.get("HOME", "/tmp"),
            "LANG": "C.UTF-8",
            "LC_ALL": "C.UTF-8",
            # Recorded streams must not vary run to run more than the program
            # itself varies.
            "NO_COLOR": "",
        }
        child_env.pop("NO_COLOR")
        child_env.update(env or {})
        os.environ.clear()
        os.environ.update(child_env)
        if cwd:
            os.chdir(cwd)
        try:
            os.execvp(argv[0], argv)
        finally:
            os._exit(127)

    set_size(fd, cols, rows)

    out = bytearray()
    resizes = []
    pending_keys = list(keys)
    pending_resize = resize
    start = time.monotonic()
    deadline = start + seconds

    while time.monotonic() < deadline:
        now = time.monotonic() - start
        while pending_keys and now >= pending_keys[0][0]:
            os.write(fd, pending_keys.pop(0)[1])
        if pending_resize and now >= pending_resize[0]:
            _, new_cols, new_rows = pending_resize
            pending_resize = None
            resizes.append(
                {"at_byte": len(out), "cols": new_cols, "rows": new_rows}
            )
            set_size(fd, new_cols, new_rows)
        ready, _, _ = select.select([fd], [], [], 0.1)
        if not ready:
            continue
        try:
            chunk = os.read(fd, 65536)
        except OSError as exc:
            if exc.errno in (errno.EIO, errno.EBADF):
                break
            raise
        if not chunk:
            break
        out += chunk

    try:
        os.kill(pid, 9)
        os.waitpid(pid, 0)
    except OSError:
        pass
    try:
        os.close(fd)
    except OSError:
        pass

    return bytes(out), resizes


def sh(script: str) -> list:
    return ["bash", "--norc", "--noprofile", "-c", script]


# Scratch material some cases page through or dump.
def _scratch(name: str, content: str) -> str:
    path = os.path.join("/tmp", "latch-vt-" + name)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return path


UNICODE_SCRIPT = r"""
printf 'ascii baseline\n'
printf 'cjk: \344\275\240\345\245\275\344\270\226\347\225\214 wide\n'
printf 'combining: e\314\201 a\314\200 o\314\210 n\314\203\n'
printf 'emoji: \360\237\232\200 \342\234\205 \360\237\216\211\n'
printf 'zwj: \360\237\221\251\342\200\215\360\237\221\251\342\200\215\360\237\221\247\n'
printf 'vs16: \342\235\244\357\270\217 vs15: \342\235\244\357\270\216\n'
printf 'mixed: [\344\275\240a\345\245\275b]\n'
printf 'even: '
printf '\346\274\242%.0s' $(seq 1 49)
printf '\n'
printf 'odd: '
printf '\346\274\242%.0s' $(seq 1 49)
printf '\n'
printf 'done\n'
"""

PROGRESS_SCRIPT = r"""
for i in $(seq 1 40); do
  printf '\r[%-20s] %3d%%' "$(printf '#%.0s' $(seq 1 $((i/2+1))))" "$((i*100/40))"
done
printf '\n'
printf '\033[s'
for i in $(seq 1 30); do
  printf '\033[u\033[Kspinner %s step %02d' "$(printf '%s' '|/-\' | cut -c$(( i % 4 + 1 )))" "$i"
done
printf '\n'
for i in $(seq 1 20); do
  printf '\033[%d;1Hrow %02d rewritten' "$((i % 10 + 5))" "$i"
done
printf '\033[20;1H\n'
"""


def case_definitions():
    long_file = _scratch(
        "pager.txt",
        "".join("line %04d %s\n" % (n, "-" * 60) for n in range(1, 400)),
    )
    return {
        # --- Real agent output -------------------------------------------
        "claude-code-startup": dict(
            argv=["claude"],
            cwd=ROOT,
            seconds=10.0,
            note="Claude Code TUI startup in a trusted directory.",
        ),
        "claude-code-trust-prompt": dict(
            argv=["claude"],
            cwd="/tmp",
            seconds=8.0,
            note=(
                "Claude Code startup in an untrusted directory: primary screen, "
                "heavy wrapping and absolute column addressing, no alternate screen."
            ),
        ),
        "claude-code-turn": dict(
            argv=["claude"],
            cwd=ROOT,
            seconds=25.0,
            keys=[(5.0, b"reply with just the word ok"), (7.0, b"\r")],
            note=(
                "A full Claude Code turn: prompt typed, submitted, spinner, "
                "status line, and the response frame."
            ),
            notes=(
                "Recorded in a container whose child processes have no Claude "
                "credentials, so the turn ends in a login-expired result frame "
                "rather than an assistant reply. Everything the emulator is "
                "being tested on is present and real — prompt echo, spinner "
                "frames, in-place status-line rewrites, OSC title updates, "
                "cursor save/restore. Re-record on an authenticated machine "
                "with `scripts/capture-vt.py claude-code-turn` to carry a model "
                "reply as well; no test needs to change."
            ),
        ),
        "claude-code-resize-alt-screen": dict(
            argv=["claude"],
            cwd=ROOT,
            seconds=14.0,
            resize=(7.0, 72, 20),
            note=(
                "Claude Code resized from 100x30 to 72x20 while the alternate "
                "screen is active; it redraws in response."
            ),
        ),
        "codex-startup": dict(
            argv=["codex"],
            cwd="/tmp",
            seconds=14.0,
            keys=[(4.0, b"2"), (5.0, b"\r")],
            note=(
                "Codex TUI startup: synchronized output brackets, kitty keyboard "
                "flags, DECRQM/DA queries, OSC 8 hyperlinks, full-viewport paint."
            ),
            notes=(
                "The recording machine has no Codex credentials, so startup "
                "lands on the sign-in screen. That screen is still a real "
                "full-viewport Codex paint and carries the sequences this suite "
                "exists to check."
            ),
        ),
        # --- Shaped cases -------------------------------------------------
        "alternate-screen-enter-exit": dict(
            argv=sh(
                "printf 'before the pager\\n'; less %s; "
                "printf 'back on the primary screen\\n'" % long_file
            ),
            seconds=8.0,
            keys=[(1.5, b" "), (2.5, b" "), (3.5, b"q")],
            note=(
                "less enters the alternate screen, is paged, then exits back to "
                "the primary screen with output after it."
            ),
        ),
        "resize-midstream": dict(
            argv=sh(
                "printf 'before the pager\\n'; less %s; "
                "printf 'back at the new width\\n'" % long_file
            ),
            seconds=8.0,
            keys=[(1.5, b" "), (4.5, b" "), (6.0, b"q")],
            resize=(3.0, 72, 18),
            note="A pager resized from 100x30 to 72x18 partway through the stream.",
        ),
        "unicode-wide-combining-emoji": dict(
            argv=sh(UNICODE_SCRIPT),
            seconds=6.0,
            note=(
                "Wide CJK, combining marks, emoji including ZWJ sequences and "
                "variation selectors, and a wide character straddling the "
                "right margin. The `even:` line divides the remaining width "
                "exactly; the `odd:` line does not, so a wide character has to "
                "wrap and leave the final column blank."
            ),
        ),
        "bracketed-paste": dict(
            argv=["bash", "--norc", "--noprofile", "-i"],
            seconds=8.0,
            keys=[
                (1.5, b"\x1b[200~echo one\necho two\x1b[201~"),
                (3.0, b"\r"),
                (4.5, b"exit\r"),
            ],
            note=(
                "An interactive readline shell enabling bracketed paste, "
                "receiving a multi-line paste, and disabling it on exit."
            ),
        ),
        "cursor-rewrite-progress": dict(
            argv=sh(PROGRESS_SCRIPT),
            seconds=8.0,
            note=(
                "A progress bar and spinner rewriting in place with carriage "
                "returns, save/restore cursor, and absolute cursor addressing."
            ),
        ),
        "high-rate-output": dict(
            argv=sh("seq 1 50000"),
            seconds=12.0,
            note=(
                "Sustained high-rate output that scrolls far past the screen, "
                "so scrollback wraps and the visible screen is a small tail."
            ),
        ),
    }


def write_case(name: str, spec: dict) -> None:
    cols = spec.get("cols", DEFAULT_COLS)
    rows = spec.get("rows", DEFAULT_ROWS)
    if shutil.which(spec["argv"][0]) is None:
        print("skip %s: %s not on PATH" % (name, spec["argv"][0]), file=sys.stderr)
        return

    data, resizes = record(
        spec["argv"],
        cwd=spec.get("cwd"),
        seconds=spec.get("seconds", 8.0),
        cols=cols,
        rows=rows,
        keys=spec.get("keys", ()),
        resize=spec.get("resize"),
        env=spec.get("env"),
    )
    if not data:
        print("skip %s: recorded no output" % name, file=sys.stderr)
        return

    case_dir = os.path.join(VT_DIR, name)
    os.makedirs(case_dir, exist_ok=True)
    with open(os.path.join(case_dir, "input.bin"), "wb") as handle:
        handle.write(data)

    meta = {
        "name": name,
        "description": spec["note"],
        "size": {"cols": cols, "rows": rows},
        "recorded": {
            "command": spec["argv"],
            "term": "xterm-256color",
            "platform": platform.system().lower(),
            "bytes": len(data),
        },
    }
    if resizes:
        meta["resizes"] = resizes
    if spec.get("notes"):
        meta["notes"] = spec["notes"]
    meta_path = os.path.join(case_dir, "meta.json")
    existing = {}
    if os.path.exists(meta_path):
        with open(meta_path, encoding="utf-8") as handle:
            existing = json.load(handle)
    # Hand-authored fields survive a re-record.
    for key in ("notes", "expected_from"):
        if key in existing:
            meta[key] = existing[key]
    with open(meta_path, "w", encoding="utf-8") as handle:
        json.dump(meta, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    print("wrote %s (%d bytes)" % (name, len(data)))


def main() -> int:
    cases = case_definitions()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("names", nargs="*", help="case names to record")
    parser.add_argument("--all", action="store_true", help="record every case")
    parser.add_argument("--list", action="store_true", help="list case names")
    args = parser.parse_args()

    if args.list:
        for name in sorted(cases):
            print(name)
        return 0

    selected = sorted(cases) if args.all else args.names
    if not selected:
        parser.print_usage(sys.stderr)
        return 2
    for name in selected:
        if name not in cases:
            print("unknown case: %s" % name, file=sys.stderr)
            return 2
        write_case(name, cases[name])
    return 0


if __name__ == "__main__":
    sys.exit(main())
