#!/usr/bin/env python3
"""Generate the Swift protocol-major-2 contract and vendored schema manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


APP = Path(__file__).resolve().parent.parent
VENDORED = APP / "Contract/schemas"
MANIFEST = APP / "Contract/manifest.json"
SWIFT = APP / "Sources/LatchMobileKit/Generated/LatchContract.swift"
DEFAULT_UPSTREAM = APP.parent.parent
NAMES = (
    "conversation-item.schema.json",
    "conversation-state.schema.json",
    "conversation-protocol.schema.json",
    "gateway-capabilities.schema.json",
    "terminal-connection.schema.json",
)
SOURCES = {
    f"schemas/remote-access/v2/{name}":
        f"https://latch.cooperativ.dev/schemas/remote-access/v2/{name}"
    for name in NAMES
}


class ContractError(SystemExit):
    pass


def load(root: Path, relative: str) -> dict:
    path = root / relative
    if not path.is_file():
        raise ContractError(f"missing contract schema: {path}")
    document = json.loads(path.read_text())
    if document.get("$id") != SOURCES[relative]:
        raise ContractError(f"{relative} has the wrong canonical $id")
    return document


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def swift_source(schema_digest: str) -> str:
    return f'''// Generated by Tools/generate-contract.py from Contract/schemas; do not edit by hand.
// Canonical schema set SHA-256: {schema_digest}
''' + '''

import Foundation

public enum LatchContract {
    public static let protocolVersion = 2
}

/// Reason carried in a terminal WebSocket close frame. `detached` is a clean
/// end; every other value says why the session's single exclusive surface was
/// taken away from this device.
public enum TerminalCloseReason: String, Codable, Sendable {
    case detached
    case stolen
    case slowClient = "slow_client"
    case sessionExited = "session_exited"
    case kernelError = "kernel_error"

    /// Application close code paired with this reason.
    public var closeCode: Int {
        switch self {
        case .detached: return 1000
        case .slowClient: return 4408
        case .stolen: return 4409
        case .sessionExited: return 4410
        case .kernelError: return 4500
        }
    }

    /// The reason for one observed close code, or `nil` when the gateway sent
    /// a code this contract does not define.
    public static func forCloseCode(_ code: Int) -> TerminalCloseReason? {
        allCases.first { $0.closeCode == code }
    }

    private static let allCases: [TerminalCloseReason] = [
        .detached, .stolen, .slowClient, .sessionExited, .kernelError
    ]
}

public struct GatewayEndpoints: Codable, Equatable, Sendable {
    public var sessions: Bool
    public var terminal: Bool
    public var conversation: Bool

    public init(sessions: Bool = false, terminal: Bool = false, conversation: Bool = false) {
        self.sessions = sessions
        self.terminal = terminal
        self.conversation = conversation
    }
}

public enum GatewayEndpointsName: String, CaseIterable, Sendable {
    case sessions
    case terminal
    case conversation
}

public extension GatewayEndpoints {
    func isEnabled(_ name: GatewayEndpointsName) -> Bool {
        switch name {
        case .sessions: return sessions
        case .terminal: return terminal
        case .conversation: return conversation
        }
    }
}

public struct GatewayFeatures: Codable, Equatable, Sendable {
    /// Always true on a current gateway: a terminal connection is the
    /// session's one exclusive surface. The field remains so this app can
    /// detect a Mac that predates the exclusive cutover and refuse it.
    public var exclusiveTerminal: Bool

    public init(exclusiveTerminal: Bool = false) {
        self.exclusiveTerminal = exclusiveTerminal
    }
}

public enum GatewayFeaturesName: String, CaseIterable, Sendable {
    case exclusiveTerminal
}

public extension GatewayFeatures {
    func isEnabled(_ name: GatewayFeaturesName) -> Bool {
        switch name { case .exclusiveTerminal: return exclusiveTerminal }
    }
}

public struct GatewayEngineCapabilities: Decodable, Equatable, Sendable {
    public var create: Bool
    public var openViewer: Bool
    public var localAttach: Bool
    public var cloudAttach: Bool
    public var selfUpdate: Bool
    public var extensions: [String]
}

public struct GatewayCapabilities: Decodable, Equatable, Sendable {
    public var protocolVersion: Int
    public var productVersion: String
    public var capabilities: GatewayEngineCapabilities
    public var endpoints: GatewayEndpoints
    public var features: GatewayFeatures
    public var gatewayInstanceId: String
    public var operationRetentionSeconds: Int

    public init(
        protocolVersion: Int,
        productVersion: String,
        capabilities: GatewayEngineCapabilities,
        endpoints: GatewayEndpoints,
        features: GatewayFeatures,
        gatewayInstanceId: String,
        operationRetentionSeconds: Int
    ) {
        self.protocolVersion = protocolVersion
        self.productVersion = productVersion
        self.capabilities = capabilities
        self.endpoints = endpoints
        self.features = features
        self.gatewayInstanceId = gatewayInstanceId
        self.operationRetentionSeconds = operationRetentionSeconds
    }
}

public enum MessageStatus: String, Codable, Sendable {
    case submitted, observed, partial, complete, failed

    public init(from decoder: Decoder) throws {
        let value = try decoder.singleValueContainer().decode(String.self)
        self = MessageStatus(rawValue: value) ?? .complete
    }
}

public enum ConversationItemKind: Equatable, Sendable, Codable {
    case message(role: String, text: String, status: MessageStatus)
    case tool(name: String, summary: String, status: String, parentMessageId: String?)
    case request(requestId: String, requestType: String, prompt: String, choices: [String], status: String)

    private enum CodingKeys: String, CodingKey {
        case type, role, text, status, name, summary, parentMessageId
        case requestId, requestType, prompt, choices
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(String.self, forKey: .type) {
        case "message":
            self = .message(
                role: try container.decode(String.self, forKey: .role),
                text: try container.decode(String.self, forKey: .text),
                status: try container.decode(MessageStatus.self, forKey: .status)
            )
        case "tool":
            self = .tool(
                name: try container.decode(String.self, forKey: .name),
                summary: try container.decode(String.self, forKey: .summary),
                status: try container.decode(String.self, forKey: .status),
                parentMessageId: try container.decodeIfPresent(String.self, forKey: .parentMessageId)
            )
        case "request":
            self = .request(
                requestId: try container.decode(String.self, forKey: .requestId),
                requestType: try container.decode(String.self, forKey: .requestType),
                prompt: try container.decode(String.self, forKey: .prompt),
                choices: try container.decode([String].self, forKey: .choices),
                status: try container.decode(String.self, forKey: .status)
            )
        default:
            throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "unknown conversation item kind")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .message(let role, let text, let status):
            try container.encode("message", forKey: .type)
            try container.encode(role, forKey: .role)
            try container.encode(text, forKey: .text)
            try container.encode(status, forKey: .status)
        case .tool(let name, let summary, let status, let parentMessageId):
            try container.encode("tool", forKey: .type)
            try container.encode(name, forKey: .name)
            try container.encode(summary, forKey: .summary)
            try container.encode(status, forKey: .status)
            try container.encodeIfPresent(parentMessageId, forKey: .parentMessageId)
        case .request(let requestId, let requestType, let prompt, let choices, let status):
            try container.encode("request", forKey: .type)
            try container.encode(requestId, forKey: .requestId)
            try container.encode(requestType, forKey: .requestType)
            try container.encode(prompt, forKey: .prompt)
            try container.encode(choices, forKey: .choices)
            try container.encode(status, forKey: .status)
        }
    }
}

public struct ConversationItem: Codable, Equatable, Identifiable, Sendable {
    public let id: String
    public let ordinal: UInt64
    /// Display metadata only. Clients order by ordinal.
    public let createdAt: String
    public let kind: ConversationItemKind
}

public struct OperationAvailability: Codable, Equatable, Sendable {
    public let enabled: Bool
    public let reason: String?
}

public struct ConnectorIdentity: Codable, Equatable, Sendable {
    public let id: String
    public let version: String
}

public struct ConversationState: Codable, Equatable, Sendable {
    public let phase: String
    public let sendMessage: OperationAvailability
    public let resolveRequest: OperationAvailability
    /// Derived from the newest pending request item.
    public let pendingRequest: String?
    public let connector: ConnectorIdentity?
}

public struct ConversationSnapshot: Codable, Equatable, Sendable {
    public let generation: String
    public let revision: UInt64
    public let operationEpoch: String
    public let items: [ConversationItem]
    public let state: ConversationState
    public let hasMoreBefore: Bool
    public let reason: String?
}

public enum ConversationServerMessage: Decodable, Equatable, Sendable {
    case snapshot(ConversationSnapshot)
    case itemsUpserted(generation: String, revision: UInt64, items: [ConversationItem])
    case itemsRemoved(generation: String, revision: UInt64, itemIds: [String])
    case stateChanged(generation: String, revision: UInt64, state: ConversationState)
    case operationResult(operationId: String, status: String, itemId: String?, reason: String?)
    case historyPage(requestId: String, items: [ConversationItem], hasMoreBefore: Bool)
    case error(code: String, message: String)

    private enum CodingKeys: String, CodingKey {
        case type, generation, revision, operationEpoch, items, state, hasMoreBefore, reason
        case itemIds, operationId, status, itemId, requestId, code, message
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        switch try container.decode(String.self, forKey: .type) {
        case "snapshot": self = .snapshot(try ConversationSnapshot(from: decoder))
        case "items_upserted": self = .itemsUpserted(
            generation: try container.decode(String.self, forKey: .generation),
            revision: try container.decode(UInt64.self, forKey: .revision),
            items: try container.decode([ConversationItem].self, forKey: .items)
        )
        case "items_removed": self = .itemsRemoved(
            generation: try container.decode(String.self, forKey: .generation),
            revision: try container.decode(UInt64.self, forKey: .revision),
            itemIds: try container.decode([String].self, forKey: .itemIds)
        )
        case "state_changed": self = .stateChanged(
            generation: try container.decode(String.self, forKey: .generation),
            revision: try container.decode(UInt64.self, forKey: .revision),
            state: try container.decode(ConversationState.self, forKey: .state)
        )
        case "operation_result": self = .operationResult(
            operationId: try container.decode(String.self, forKey: .operationId),
            status: try container.decode(String.self, forKey: .status),
            itemId: try container.decodeIfPresent(String.self, forKey: .itemId),
            reason: try container.decodeIfPresent(String.self, forKey: .reason)
        )
        case "history_page": self = .historyPage(
            requestId: try container.decode(String.self, forKey: .requestId),
            items: try container.decode([ConversationItem].self, forKey: .items),
            hasMoreBefore: try container.decode(Bool.self, forKey: .hasMoreBefore)
        )
        case "error": self = .error(
            code: try container.decode(String.self, forKey: .code),
            message: try container.decode(String.self, forKey: .message)
        )
        default: throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "unknown server message")
        }
    }
}

public enum ConversationClientMessage: Encodable, Equatable, Sendable {
    case resume(generation: String?, afterRevision: UInt64?)
    case sendMessage(operationEpoch: String, operationId: String, text: String)
    case resolveRequest(operationEpoch: String, operationId: String, requestId: String, choice: String)
    case historyRequest(requestId: String, beforeOrdinal: UInt64, limit: Int)

    private enum CodingKeys: String, CodingKey {
        case type, generation, afterRevision, operationEpoch, operationId, text
        case requestId, choice, beforeOrdinal, limit
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .resume(let generation, let afterRevision):
            try container.encode("resume", forKey: .type)
            try container.encodeIfPresent(generation, forKey: .generation)
            try container.encodeIfPresent(afterRevision, forKey: .afterRevision)
        case .sendMessage(let operationEpoch, let operationId, let text):
            try container.encode("send_message", forKey: .type)
            try container.encode(operationEpoch, forKey: .operationEpoch)
            try container.encode(operationId, forKey: .operationId)
            try container.encode(text, forKey: .text)
        case .resolveRequest(let operationEpoch, let operationId, let requestId, let choice):
            try container.encode("resolve_request", forKey: .type)
            try container.encode(operationEpoch, forKey: .operationEpoch)
            try container.encode(operationId, forKey: .operationId)
            try container.encode(requestId, forKey: .requestId)
            try container.encode(choice, forKey: .choice)
        case .historyRequest(let requestId, let beforeOrdinal, let limit):
            try container.encode("history_request", forKey: .type)
            try container.encode(requestId, forKey: .requestId)
            try container.encode(beforeOrdinal, forKey: .beforeOrdinal)
            try container.encode(limit, forKey: .limit)
        }
    }
}
'''


def outputs(root: Path) -> dict[Path, str]:
    files: dict[Path, str] = {}
    entries = []
    schema_texts = []
    for relative in SOURCES:
        text = (root / relative).read_text()
        load(root, relative)
        files[VENDORED / Path(relative).name] = text
        schema_texts.append(text)
        entries.append({"source": relative, "sha256": digest(text)})
    source = swift_source(digest("".join(schema_texts)))
    files[SWIFT] = source
    files[MANIFEST] = json.dumps({
        "protocolVersion": 2,
        "generator": "Tools/generate-contract.py",
        "generated": {"path": str(SWIFT.relative_to(APP)), "sha256": digest(source)},
        "schemas": entries,
    }, indent=2) + "\n"
    return files


class VendoredRoot:
    def __truediv__(self, relative: str | Path) -> Path:
        return VENDORED / Path(relative).name


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--upstream", type=Path)
    args = parser.parse_args()
    root: Path = args.upstream or (VendoredRoot() if args.check else DEFAULT_UPSTREAM)  # type: ignore[assignment]
    files = outputs(root)
    if args.check:
        stale = [path for path, text in files.items() if not path.is_file() or path.read_text() != text]
        if stale:
            raise ContractError("generated Swift contract is stale: " + ", ".join(str(path.relative_to(APP)) for path in stale))
        if args.upstream:
            drifted = [relative for relative in SOURCES if (args.upstream / relative).read_text() != (VENDORED / Path(relative).name).read_text()]
            if drifted:
                raise ContractError("vendored contract drift: " + ", ".join(drifted))
        print("contract is current")
        return
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


if __name__ == "__main__":
    main()
