import Foundation
import Network
import Security

/// The mechanism that makes the gateway URL usable.
public protocol GatewayTransport: Sendable {
    var gatewayLink: GatewayLink { get }
    /// Stops accepting local connections and discards any capability.
    func stop()
}

public extension GatewayTransport {
    func stop() {}
}

/// A gateway stream whose peer authentication and multiplexing are already
/// owned by the shared Rust Remote Link core.
public protocol AuthenticatedGatewayChannel: Sendable {
    func read() async throws -> Data
    func write(_ bytes: Data) async throws
    func close() async
}

public protocol AuthenticatedGatewayChannelProvider: Sendable {
    func openGatewayChannel() async throws -> any AuthenticatedGatewayChannel
}

/// Installs a listener handler before the listener starts while allowing its
/// owner to be constructed after Network.framework selects the ephemeral port.
final class DeferredConnectionHandler<Connection>: @unchecked Sendable {
    typealias Handler = @Sendable (Connection) -> Void

    private let lock = NSLock()
    private var pending: [Connection] = []
    private var handler: Handler?

    func receive(_ connection: Connection) {
        lock.lock()
        guard let handler else {
            pending.append(connection)
            lock.unlock()
            return
        }
        lock.unlock()
        handler(connection)
    }

    func install(_ handler: @escaping Handler) {
        lock.lock()
        precondition(self.handler == nil, "the deferred connection handler was installed twice")
        self.handler = handler
        let queued = pending
        pending.removeAll(keepingCapacity: false)
        lock.unlock()
        queued.forEach(handler)
    }
}

public enum RemoteLinkTransportError: Error, Equatable, Sendable, LocalizedError {
    case listenerUnavailable
    case invalidCapability
    case malformedRequest
    case requestHeaderTooLarge
    case closed

    public var errorDescription: String? { message }

    public var message: String {
        switch self {
        case .listenerUnavailable:
            return "The phone could not start its local secure connection."
        case .invalidCapability:
            return "The local Remote Link capability was missing or invalid."
        case .malformedRequest:
            return "The local secure connection received an incomplete HTTP request."
        case .requestHeaderTooLarge:
            return "The local secure connection received an HTTP request header that is too large."
        case .closed:
            return "The secure connection closed before the request completed."
        }
    }
}

/// Guards a continuation against being resumed twice by listener callbacks.
final class ContinuationGuard: @unchecked Sendable {
    private let lock = NSLock()
    private var completed = false

    var isCompleted: Bool {
        lock.lock()
        defer { lock.unlock() }
        return completed
    }

    func markCompleted() -> Bool {
        lock.lock()
        defer { lock.unlock() }
        guard !completed else { return false }
        completed = true
        return true
    }
}

/// Receives content-free stage timings from the adapter: how long a logical
/// stream took to open and how long a response took to complete.
public typealias LinkStageRecorder = @Sendable (LinkStageSample) -> Void

/// Capability-protected loopback adapter for a Rust-owned Remote Link stream.
///
/// One instance lives per link generation. Suspending the app stops it and
/// discards its capability; resuming starts a new one with a new random
/// capability and a new ephemeral port, so a token that leaked while the app
/// was backgrounded opens nothing afterwards.
public final class RemoteLinkGatewayTransport: GatewayTransport, @unchecked Sendable {
    /// Marks a 502 generated by the phone rather than by the Mac gateway.
    static let tunnelFailureCode = "remote_link_unreachable"

    public let gatewayLink: GatewayLink

    private let listener: NWListener
    private let provider: any AuthenticatedGatewayChannelProvider
    private let capability: String
    private let recorder: LinkStageRecorder?
    private let queue = DispatchQueue(label: "dev.cooperativ.latch.remote-link-loopback")
    private let stopped = ContinuationGuard()

    private init(
        listener: NWListener,
        provider: any AuthenticatedGatewayChannelProvider,
        capability: String,
        gatewayLink: GatewayLink,
        recorder: LinkStageRecorder?
    ) {
        self.listener = listener
        self.provider = provider
        self.capability = capability
        self.gatewayLink = gatewayLink
        self.recorder = recorder
    }

    /// The listener's capability, for tests proving rotation. Never logged.
    var capabilityForTesting: String { capability }

    /// True once `stop()` ran; a stopped adapter refuses every connection.
    public var isStopped: Bool { stopped.isCompleted }

    deinit {
        listener.cancel()
    }

    public static func start(
        authenticatedProvider: any AuthenticatedGatewayChannelProvider,
        pairedDevice: PairedDeviceRecord,
        recorder: LinkStageRecorder? = nil
    ) async throws -> RemoteLinkGatewayTransport {
        guard pairedDevice.isActive else { throw RemoteLinkTransportError.closed }
        let listenerAndLink = try await makeLoopbackListener()
        let transport = RemoteLinkGatewayTransport(
            listener: listenerAndLink.listener,
            provider: authenticatedProvider,
            capability: listenerAndLink.capability,
            gatewayLink: listenerAndLink.link,
            recorder: recorder
        )
        listenerAndLink.router.install { [weak transport] connection in
            guard let transport else {
                connection.cancel()
                return
            }
            Task { await transport.accept(connection) }
        }
        return transport
    }

    public func stop() {
        _ = stopped.markCompleted()
        listener.cancel()
    }

    private static func makeLoopbackListener() async throws -> (
        listener: NWListener,
        link: GatewayLink,
        capability: String,
        router: DeferredConnectionHandler<NWConnection>
    ) {
        let parameters = NWParameters.tcp
        parameters.requiredLocalEndpoint = .hostPort(
            host: .ipv4(IPv4Address("127.0.0.1")!),
            port: .any
        )
        let listener = try NWListener(using: parameters, on: .any)
        let router = DeferredConnectionHandler<NWConnection>()
        listener.newConnectionHandler = { connection in router.receive(connection) }
        try await waitUntilReady(listener)
        guard let port = listener.port else { throw RemoteLinkTransportError.listenerUnavailable }
        let capability = try randomCapability()
        return (
            listener,
            GatewayLink(
                url: URL(string: "http://127.0.0.1:\(port.rawValue)")!,
                token: capability
            ),
            capability,
            router
        )
    }

    private static func randomCapability() throws -> String {
        var bytes = [UInt8](repeating: 0, count: 32)
        guard SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) == errSecSuccess else {
            throw RemoteLinkTransportError.listenerUnavailable
        }
        return bytes.map { String(format: "%02x", $0) }.joined()
    }

    private static func waitUntilReady(_ listener: NWListener) async throws {
        try await withCheckedThrowingContinuation { continuation in
            let completion = ContinuationGuard()
            listener.stateUpdateHandler = { state in
                switch state {
                case .ready:
                    guard completion.markCompleted() else { return }
                    continuation.resume(returning: ())
                case .failed, .cancelled:
                    guard completion.markCompleted() else { return }
                    continuation.resume(throwing: RemoteLinkTransportError.listenerUnavailable)
                default:
                    break
                }
            }
            listener.start(queue: DispatchQueue(label: "dev.cooperativ.latch.remote-link-listener"))
        }
    }

    private func accept(_ loopback: NWConnection) async {
        guard !stopped.isCompleted else {
            loopback.cancel()
            return
        }
        loopback.start(queue: queue)
        do {
            var validator = TunnelRequestValidator(expectedCapability: capability)
            while true {
                let bytes = try await loopback.receiveData()
                if let firstRequest = try validator.append(bytes) {
                    try await bridge(loopback: loopback, firstRequest: firstRequest)
                    return
                }
            }
        } catch let error as RemoteLinkTransportError {
            await reject(loopback, reason: error.message)
        } catch {
            await reject(loopback, reason: error.localizedDescription)
        }
    }

    private func bridge(loopback: NWConnection, firstRequest: Data) async throws {
        let opening = Date()
        let channel: any AuthenticatedGatewayChannel
        do {
            channel = try await provider.openGatewayChannel()
        } catch {
            recorder?(LinkStageSample(stage: .streamOpen, milliseconds: Self.millis(since: opening), outcome: .failed))
            throw error
        }
        recorder?(LinkStageSample(stage: .streamOpen, milliseconds: Self.millis(since: opening)))
        defer {
            Task { await channel.close() }
            loopback.cancel()
        }
        try await channel.write(firstRequest)
        let recorder = self.recorder
        try await withThrowingTaskGroup(of: Void.self) { group in
            group.addTask {
                while !Task.isCancelled {
                    try await channel.write(try await loopback.receiveData())
                }
            }
            group.addTask {
                var first: Date?
                while !Task.isCancelled {
                    do {
                        let bytes = try await channel.read()
                        if first == nil { first = Date() }
                        try await loopback.sendData(bytes)
                    } catch {
                        // Normal EOF after a complete response is what ends
                        // this reader; the sample measures first byte to last.
                        if let first {
                            recorder?(LinkStageSample(stage: .responseComplete, milliseconds: Self.millis(since: first)))
                        }
                        throw error
                    }
                }
            }
            do {
                _ = try await group.next()
            } catch {
                await channel.close()
                loopback.cancel()
                group.cancelAll()
                throw error
            }
            await channel.close()
            loopback.cancel()
            group.cancelAll()
        }
    }

    private static func millis(since date: Date) -> UInt64 {
        UInt64(max(0, Date().timeIntervalSince(date) * 1000))
    }

    private func reject(_ connection: NWConnection, reason: String) async {
        let body = (try? JSONSerialization.data(withJSONObject: [
            "error": Self.tunnelFailureCode,
            "reason": reason
        ])).flatMap { String(data: $0, encoding: .utf8) } ?? reason
        let response = "HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: \(body.utf8.count)\r\n\r\n\(body)"
        try? await connection.sendData(Data(response.utf8))
        connection.cancel()
    }
}

/// Requires the unguessable per-listener capability and strips it before any
/// bytes enter Remote Link. The Mac therefore receives no phone-local bearer.
struct TunnelRequestValidator {
    private static let maxHeaderBytes = 64 * 1024
    private let expectedAuthorization: String
    private var pending = Data()
    private var accepted = false

    init(expectedCapability: String) {
        expectedAuthorization = "Bearer \(expectedCapability)"
    }

    mutating func append(_ bytes: Data) throws -> Data? {
        guard !accepted else { return bytes }
        pending.append(bytes)
        guard pending.count <= Self.maxHeaderBytes else {
            throw RemoteLinkTransportError.requestHeaderTooLarge
        }
        guard let end = pending.range(of: Data("\r\n\r\n".utf8)) else { return nil }
        let header = pending[..<end.lowerBound]
        guard let text = String(data: header, encoding: .utf8) else {
            throw RemoteLinkTransportError.malformedRequest
        }
        let lines = text.components(separatedBy: "\r\n")
        guard let requestLine = lines.first, !requestLine.isEmpty else {
            throw RemoteLinkTransportError.malformedRequest
        }
        var authorizationCount = 0
        var sanitized = [requestLine]
        for line in lines.dropFirst() {
            guard let colon = line.firstIndex(of: ":") else {
                throw RemoteLinkTransportError.malformedRequest
            }
            let name = line[..<colon].trimmingCharacters(in: .whitespaces).lowercased()
            let value = line[line.index(after: colon)...]
                .trimmingCharacters(in: .whitespaces)
            if name == "proxy-authorization" {
                throw RemoteLinkTransportError.invalidCapability
            }
            if name == "authorization" {
                authorizationCount += 1
                guard authorizationCount == 1, value == expectedAuthorization else {
                    throw RemoteLinkTransportError.invalidCapability
                }
                continue
            }
            sanitized.append(line)
        }
        guard authorizationCount == 1 else { throw RemoteLinkTransportError.invalidCapability }
        let body = pending[end.upperBound...]
        var result = Data((sanitized.joined(separator: "\r\n") + "\r\n\r\n").utf8)
        result.append(body)
        accepted = true
        pending.removeAll(keepingCapacity: false)
        return result
    }
}

private extension NWConnection {
    func receiveData(maximumLength: Int = 16 * 1024) async throws -> Data {
        try await withCheckedThrowingContinuation { continuation in
            receive(minimumIncompleteLength: 1, maximumLength: maximumLength) {
                data, _, complete, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let data, !data.isEmpty {
                    continuation.resume(returning: data)
                } else if complete {
                    continuation.resume(throwing: RemoteLinkTransportError.closed)
                } else {
                    continuation.resume(throwing: RemoteLinkTransportError.closed)
                }
            }
        }
    }

    func sendData(_ data: Data) async throws {
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            send(content: data, completion: .contentProcessed { error in
                if let error {
                    continuation.resume(throwing: error)
                } else {
                    continuation.resume()
                }
            })
        }
    }
}

/// Bonjour supplies untrusted LAN coordinates only. Rust authenticates the
/// exact paired Mac key before opening a logical service.
public final class BonjourMacDiscovery: @unchecked Sendable {
    public static let serviceType = "_latch-remote._tcp"

    public init() {}

    public func remoteLinkTargets(
        matching pinnedMacPublicKey: String,
        for duration: Duration = .milliseconds(250)
    ) async -> [RemoteLinkLanTarget] {
        let pin = pinnedMacPublicKey.lowercased()
        guard pin.count == 64, pin.allSatisfy({ $0.isHexDigit }) else { return [] }
        let parameters = NWParameters.tcp
        parameters.includePeerToPeer = true
        let browser = NWBrowser(for: .bonjour(type: Self.serviceType, domain: nil), using: parameters)
        let collector = RemoteLinkLanTargetCollector()
        browser.browseResultsChangedHandler = { results, _ in
            let targets = results.compactMap { result -> RemoteLinkLanTarget? in
                guard case let .bonjour(record) = result.metadata,
                      record["identityKey"]?.lowercased() == pin,
                      record["linkVersion"] == "1",
                      let host = record["lanHost"], !host.isEmpty,
                      let portText = record["lanPort"],
                      let port = UInt16(portText), port != 0
                else { return nil }
                return RemoteLinkLanTarget(host: host, port: port)
            }
            Task { await collector.replace(with: targets) }
        }
        browser.start(queue: DispatchQueue(label: "dev.cooperativ.latch.remote-link-bonjour"))
        defer { browser.cancel() }
        try? await Task.sleep(for: duration)
        return await collector.values
    }
}

public struct RemoteLinkLanTarget: Equatable, Sendable {
    public let host: String
    public let port: UInt16

    public init(host: String, port: UInt16) {
        self.host = host
        self.port = port
    }
}

private actor RemoteLinkLanTargetCollector {
    private(set) var values: [RemoteLinkLanTarget] = []

    func replace(with values: [RemoteLinkLanTarget]) {
        self.values = values
    }
}
